import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";
import { MARKUP_CENTS, supplierCents, retailPrice } from "../shared/pricing.mjs";
export { MARKUP_CENTS, supplierCents, retailPrice } from "../shared/pricing.mjs";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const APP_ID = "69386f6ce9fe29121d66f65f";
const SUPPLIER = "https://miccamisasdetime.com.br";
const PAGE_LIMIT = 5000;

import { buildCatalog } from "../shared/catalog-core.mjs";
export { buildCatalog, normalize, normalizeSize } from "../shared/catalog-core.mjs";

async function getJson(url, headers = {}) {
  let error;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const response = await fetch(url, { headers: { Accept: "application/json", ...headers }, signal: AbortSignal.timeout(45000) });
      if (!response.ok) throw new Error(`HTTP ${response.status} em ${new URL(url).pathname}`);
      return await response.json();
    } catch (cause) {
      error = cause;
      if (attempt < 2) await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 1500));
    }
  }
  throw error;
}

async function entity(name) {
  const result = await getJson(`https://base44.app/api/apps/${APP_ID}/entities/${name}?sort=-created_date&limit=${PAGE_LIMIT}`, { "X-App-Id": APP_ID });
  if (!Array.isArray(result) || result.length >= PAGE_LIMIT) throw new Error(`Resposta incompleta de ${name}; catálogo anterior preservado.`);
  return result;
}

async function supplierCatalog() {
  const products = [];
  const seen = new Set();
  for (let page = 1; page <= 100; page++) {
    const response = await getJson(`${SUPPLIER}/products.json?limit=250&page=${page}`);
    if (!Array.isArray(response.products)) throw new Error("Catálogo MIC inválido.");
    for (const product of response.products) {
      if (seen.has(product.id)) throw new Error("Paginação MIC repetiu produtos.");
      seen.add(product.id);
      products.push(product);
    }
    if (response.products.length < 250) return products;
  }
  throw new Error("Paginação MIC incompleta.");
}

async function main() {
  const mappings = JSON.parse(await readFile(path.join(ROOT, "scripts/catalog-mappings.json"), "utf8"));
  const [models, teams, countries, supplierProducts] = await Promise.all([
    entity("Model"), entity("Team"), entity("Country"), supplierCatalog(),
  ]);
  const { products, metadata, report } = buildCatalog({ models, teams, countries, supplierProducts, mappings });
  const serialize = value => JSON.stringify(value).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  const output = `// Generated by scripts/sync-catalog.mjs. Do not edit prices here.\nwindow.HYPE_ELITE_CATALOG_META=${serialize(metadata)};\nwindow.HYPE_ELITE_CATALOG_PRODUCTS=${serialize(products)};\n`;
  await mkdir(path.join(ROOT, "assets/js"), { recursive: true });
  await writeFile(path.join(ROOT, "assets/js/catalog-products.js"), output);
  console.log(JSON.stringify({ ...metadata, ...report }, null, 2));
  if (process.env.GITHUB_STEP_SUMMARY) {
    const summary = `## Catálogo Hype Elite\n\n${metadata.modelCount} modelos, ${metadata.pricedCount} com preço confirmado, ${metadata.availableCount} disponíveis e ${metadata.photoCount} fotos.\n\nPreço normal MIC + R$75,00 por produto/kit. Frete grátis.\n\n${report.unpriced.length ? "### Sem preço atual (venda bloqueada)\n" + report.unpriced.map(item => `- ${item.name}`).join("\n") : "Todos os modelos têm preço de origem confirmado."}\n`;
    await writeFile(process.env.GITHUB_STEP_SUMMARY, summary, { flag: "a" });
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().catch(error => { console.error(error.message); process.exitCode = 1; });
}
